import colorama
from colorama import Fore, Back, Style
colorama.init(autoreset=True)
def visial_output():
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░Clear Altitude░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░Max {alt_rime}░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░Clouds░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░Min {cloud_base}░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░Clear Altitude░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
