import colorama
from colorama import Fore, Back, Style
colorama.init(autoreset=True)
def visual_output():
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░Low Risk░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░Max {alt_rime}░░░░░░░░░░░░░█-20C')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█-15C')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█-10C')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.RED}█░░░░░░░░░░░Min {cloud_base}░░░░░░░░░░░█ 0C')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░No risk of icing░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
    print(f'{Fore.GREEN}█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█')
